name: Build ruleset and geodata
on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
        shell: bash

      - name: Clone Repository
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./custom/go.sum

      - name: Generate `sing-box` rule-set
        run: |
          mkdir -p ./sing-box-ruleset/
          archs1=(Apple Bing ChinaDomain GoogleCN GoogleFCM LocalAreaNetwork Microsoft OneDrive OpenAi ProxyGFWlist ProxyMedia Speedtest Spotify Telegram TikTok YouTube)
          archs2=(Apple-IP ChinaCompanyIp ChinaDomain-IP GoogleFCM-IP LocalAreaNetwork-IP ProxyGFWlist-IP ProxyMedia-IP Telegram-IP)
          archs3=(private_direct private_proxy Emby)

          # Ready for generate `sing-box` rule_set
          for((i=0;i<17;i++)); do
            mkdir -p "./tools/rules/${archs1[i]}/"
            mkdir -p "./tools/rules/${archs2[i]}/"
            mkdir -p "./tools/rules/${archs3[i]}/"
            curl "https://raw.githubusercontent.com/wuyuqq/domain-list-custom/domains/${archs1[i]}.list" > "./tools/rules/${archs1[i]}/${archs1[i]}.yaml"
            curl "https://raw.githubusercontent.com/wuyuqq/domain-list-custom/domains/${archs2[i]}.list" > "./tools/rules/${archs2[i]}/${archs2[i]}.yaml"
            curl "https://raw.githubusercontent.com/wuyuqq/domain-list-custom/domains/${archs3[i]}.list" > "./tools/rules/${archs3[i]}/${archs3[i]}.yaml"
          done

      - name: Download and unzip `sing-box core`
        run: |
          sing_box_version=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases | grep 'tag_name' | grep 'alpha' | head -n 1 | sed -e 's/.*v//' -e 's/".*//')
          wget "https://github.com/SagerNet/sing-box/releases/download/v${sing_box_version}/sing-box-${sing_box_version}-linux-amd64v3.tar.gz" -O - | tar -zxf - -C ./tools/
          mv -f ./tools/sing-box-${sing_box_version}-linux-amd64v3/sing-box ./tools/

      - name: Generate `sing-box` rule_set
        run: |
          cd ./tools/
          chmod +x convert.sh && ./convert.sh
          rm -rf ./sing-box* LICENSE ./rules*
          cp -f ./*.json ./*.srs ../sing-box-ruleset/

      - name: Commit and push `sing-box-ruleset` branch
        run: |
          cd ./sing-box-ruleset/ || exit 1
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b sing-box-ruleset
          git add . && git commit -m "sing-box rule_set 规则集文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin sing-box-ruleset
